broker01:
  image: redis
  expose:
    - "6379:6379"

es01:
  image: elasticsearch
  expose:
    - "9300"
  ports:
    - "9200:9200"

  volumes:
    - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    - ./es01data:/usr/share/elasticsearch/data

shipper:
  image: logstash
  ports:
    - "10514:10514"
    - "11514:11514"
    - "12514:12514"
    - "13514:13514"
    - "14514:14514"
    - "1514:1514"
  volumes:
    - ./shipper.conf:/shipper.conf
    - ./logstash_patterns:/logstash_patterns
  links:
    - broker01
  command: logstash -f /shipper.conf

indexer:
  image: logstash
  volumes:
    - ./indexer.conf:/indexer.conf
  links:
    - broker01
    - es01
  command: logstash -f /indexer.conf

kibana:
  image: kibana
  volumes:
    - ./kibana.yml:/opt/kibana/config/kibana.yml
  expose:
    - 5601
  links:
    - es01

proxy:
  image: nginx
  volumes:
    - ./nginx/conf:/etc/nginx
    - ./nginx/logs:/logs
  ports:
    - 8080:8080
  links:
    - kibana
